### ISSUE TITLE
Update julia

### ISSUE THREAD

**Issue by phelipe** [phelipe/Fuzzy.jl#1]
Update code to julia 1.0

**Comment by TheAnig** [comment]
Yo I got this

**Comment by phelipe** [comment]
Hi @TheAnig ! Can you make a pull request?

**Comment by TheAnig** [comment]
Yup, working on updating the code base, once I'm done with updating it I'll submit a PR. I will then prioritize adding docs.

**Comment by phelipe** [comment]
Ok :),I am working in a MIMO version of the package at the moment.

**Comment by Sov-trotter** [comment]
This has been around for quite sometime now. Although I'm already done with hactoberfest, but I managed to update the code to julia 1.x . Generating a PR. Please review. :)

**Comment by Sov-trotter** [comment]
You might consider closing this issue now. :)

**Comment by phelipe** [comment]
Done! :D

**Comment by phelipe** [comment]
Thanks Guys!
