### ISSUE TITLE
NaN result when values supplied ar outside of trapezoidMF

### ISSUE THREAD

**Issue by adicara** [phelipe/Fuzzy.jl#16]
@phelipe  thank you for your all your work on this package. Taking the example of the tipping problem, when I supply input values which are outside of the range of the MF I get a NaN in the FIS evaluation. Is this expected or am I doing something wrong?
I simplified the tipping problem with 1 MF and 1 rule below.

```julia
service = Dict( "poor"      => TrapezoidalMF(0.0, 0.0, 2.0, 4.0), 
                "good"      => TriangularMF(3., 5., 7.))

inputs = [service]

tip  = Dict("cheap"     => TrapezoidalMF(10., 10., 20., 30.),
            "average"   => TriangularMF(20., 30., 40.), 
            "generous"  => TrapezoidalMF(30., 40, 50., 50.))

rule1 = Rule(["poor"], "cheap")
rules = [rule1]

fis_tips = FISMamdani(inputs, tip, rules)
```
The MF for service looks as follows:
<img src=https://user-images.githubusercontent.com/2254500/128313379-29d0bc28-e3c1-4733-89e3-9b2d3403cec6.png  width="250" height="150">

First I tried to supply a value comprised within the "poor" trapezoid
```julia
in_vals = [2.5]
println(eval_fis(fis_tips, in_vals))
```
`result = 16.25`, which indeed matches with the "cheap" tip
However when I supply a value at the edge of the "poor" trapezoid or beyond I get `NaN` 
```julia
in_vals = [4.]
println(eval_fis(fis_tips, in_vals))
```
`result = NaN`

```julia
in_vals = [5.]
println(eval_fis(fis_tips, in_vals))
```
`result = NaN`

**Comment by phelipe** [comment]
This is strange, I will try figure out what is going on and see how to fix it

**Comment by adicara** [comment]
It seems to happen in the `defuzz` function when the `sum(firing_strengths) = 0` then you get a division by 0 in 
`(mean_vec' * firing_strengths)[1] / sum(firing_strengths)`

**Comment by phelipe** [comment]
Sorry for the long delay response. I think i solve the problem in branch "refactor", could you test it?

**Comment by phelipe** [comment]
@JuliaRegistrator register()
