### ISSUE TITLE
change indmax to argmax

### ISSUE THREAD

**Issue by adicara** [phelipe/Fuzzy.jl#17]
@phelipe in the defuzz function there is a call to `indmax`. In the version of Julia I am using (1.6.2) it gives me `UndefVarError: indmax not defined`. I am new to Julia, but I think this ought to be changed to `argmax`

**Comment by phelipe** [comment]
You are right.I will try to start a patch to fix this issues during the week.

**Comment by phelipe** [comment]
closed by #18
