### ISSUE TITLE
Ploting membership functions

### ISSUE THREAD

**Issue by pierrethiriet** [phelipe/Fuzzy.jl#19]
Dear Phelipe,
Sorry to bring back the question of plotting. But, I just wanted to give a small feedback.
First, I realise that it was simpler to use Fuzzy `eval` than trying to work with the MF control points:
```julia
# Membership functions 
mf_tri = TriangularMF(1, 2, 3)
mf_gauss = GaussianMF(5, 2)

# Plot MF (CairoMakie)
x = range(0, 10, length=1000)
fig = Figure()
ax = Axis(fig[1,1])
lines!(ax, x, map(x->Fuzzy.eval(mf_gauss, x), x), color=:red)
lines!(ax, x, map(x->Fuzzy.eval(mf_tri, x), x), color=:green)
fig
```
![plot_8](https://user-images.githubusercontent.com/33446598/139835583-5a8b608c-7e19-4084-84e7-d22236eefa4d.png)

My only problem is related to the fact that the MF are stored as _dictionnary_.
```julia
# Temperatures
temp = Dict("cold" => TrapezoidalMF(-12., -12., 0., 1.), 
            "cool" => TrapezoidalMF(0., 1., 10., 15.),
            "warm" => TrapezoidalMF(10., 15., 18., 23.),
            "hot"  => TrapezoidalMF(18., 23., 30., 30.))
```
Thus, when creating a plot function that will take membership functions (`plotMF(MF; colors, label...)`) , it is not possible to pass parameters in the shape of an array, e.g. colors=["#4575b4", "#91bfdb", "#999999", "#ef8a62"] as the order of the MF is unpredictible.  
So I wondered if it would be possible to use an ordered dict such [OrderedCollections.jl](https://github.com/JuliaCollections/OrderedCollections.jl) ?
Or to directly add some complementary parameter during the definition of the membership function dict:
```julia
temp = Dict("cold" => (mf=TrapezoidalMF(-12., -12., 0., 1.), label="Cold", color="#4575b4"), 
            "cool" => (mf=TrapezoidalMF(0., 1., 10., 15.), label="Cool", color="#91bfdb"),
            "warm" => (mf=TrapezoidalMF(10., 15., 18., 23.), label="Warm", color="#999999"),
            "hot"  => (mf=TrapezoidalMF(18., 23., 30., 30.), label="Hot", color="#ef8a62"))
```
Thanks a lot.

**Comment by phelipe** [comment]
Hi! Sorry for the late reply, too many task in my job. You gave me a idea about how to export points to be used in plot packages with the line below

```julia
lines!(ax, x, map(x->Fuzzy.eval(mf_gauss, x), x), color=:red)
```

I will try implement this weekend.

**Comment by phelipe** [comment]
Hi @pierrethiriet , good news. I started a implementation to return the points of membership functions, I think I can finish it in the next 8 days.

**Comment by pierrethiriet** [comment]
Good news ! Thanks a lot.

**Comment by phelipe** [comment]
@pierrethiriet  something like showed bellow is ok for you? 

```julia
using Fuzzy
using Plots

input = Dict("small" => TriangularMF(1, 2, 3), "large" => TriangularMF(4, 5, 6))
x = range(0, 8, length = 100)

data = chart_prepare(input, x)
plot(x, data["values"])
```

![image](https://user-images.githubusercontent.com/7537350/141695699-e942dca1-2a42-4f7b-8085-a661b8d07f8e.png)

**Comment by pierrethiriet** [comment]
Very sorry for this late reply.
Yes, this could definitively work!
But, could we potentially pass additional parameters in the `chart_prepare()` function such as color, label, etc ?

**Comment by phelipe** [comment]
No, the package only generates points and a vector of names. The package
doesn't know what plot package is being used, because of this I would like
only to generate the array of points to be used in any plot package.

Em sex., 19 de nov. de 2021 às 05:04, pierrethiriet <
***@***.***> escreveu:

**Comment by pierrethiriet** [comment]
I understand. It makes sense not to be bound to any plotting packages.
The trouble was to get the "_points and a vector of names_"   in the original order, a problem now solved by using OrderDict from [OrderedCollections](https://github.com/JuliaCollections/OrderedCollections.jl) instead of a standard dictionary for defining a set of MF

```julia
temp = OrderedDict("cold" => TrapezoidalMF(-12., -12., 0., 1.), 
            "cool" => TrapezoidalMF(0., 1., 10., 15.),
            "warm" => TrapezoidalMF(10., 15., 18., 23.),
            "hot"  => TrapezoidalMF(18., 23., 30., 30.))
```

This will ensure to get the MF in the set of MF in the original order which is useful in this specific use-case:

```julia
function PlotMF(MF; univers, color = nothing)
    # Figure setup
    fig = Figure(resolution=(800, 600))
    # Axis setup
    ax = Axis(fig[1,1], xlabel="Values", ylabel="Membership Grade")
    # x values
    x = range(univers[1], univers[2], length=1000)
    # Color index
    color_idx = 1
    for (key, value) in MF # Loop over 
        # Estimate values
        y = map(x->Fuzzy.eval(value, x), x)
        # Line
        lines!(ax, x, y, linewidth=3, color=color[color_idx])
        color_idx += 1
    end
    return fig
end
```

```julia
PlotMF(temp, univers=[-5,30], 
    color=["#4575b4", "#91bfdb", "#999999", "#ef8a62"])
```
![plot_2](https://user-images.githubusercontent.com/33446598/142641989-657cb5b2-5f82-407d-b501-f9bf32563f55.png)

I am not sure if it helps, but at least it simplifies the code of my on projet !

**Comment by phelipe** [comment]
The implementation return in the exact same order of the input, if the input is

Dict("small" => TriangularMF(1, 2, 3), "large" => TriangularMF(4, 5, 6))

it will return a vector of names like ["small", "large"] as well a vector of vectors [ [points of small set], [points of large set]].

**Comment by pierrethiriet** [comment]
Perfect then ! Thnaks a lot.

**Comment by phelipe** [comment]
@JuliaRegistrator register()

**Comment by phelipe** [comment]
@pierrethiriet solution merged.
