### ISSUE TITLE
installation fails in julia 1.4.1

### ISSUE THREAD

**Issue by michaelmusty** [phelipe/Fuzzy.jl#6]
`Pkg.clone("git://github.com/phelipe/Fuzzy.jl.git")`

no longer seems to work in version 1.4.1. Maybe this is an easy fix?

**Comment by phelipe** [comment]
I updated README and package. Can you try the new installation method?

**Comment by michaelmusty** [comment]
Yep. That works for me. Funny I thought I tried that. Thanks for the help in any case!

**Comment by phelipe** [comment]
:D
