### ISSUE TITLE
ANFIS

### ISSUE THREAD

**Issue by michaelmusty** [phelipe/Fuzzy.jl#7]
This is more of a feature request than an issue, but a Julia implementation of ANFIS (paper attached) could be a worthwhile application of this package. I'm happy to help work on it if there is interest.
[anfis.pdf](https://github.com/phelipe/Fuzzy.jl/files/4896627/anfis.pdf)

**Comment by phelipe** [comment]
Hi, I read the paper and I think all process can be done using Flux.jl without necessity os using Fuzzy.jl . You just have to create the layers using the functions described in the paper.

**Comment by michaelmusty** [comment]
Thanks @phelipe. I'm still trying to work out how to implement this in Flux using the membership functions from Fuzzy.jl, but I guess there's nothing to be done in this package, so I'll close the issue. Happy to chat more if I have some success with this and you are interested, and if anything comes of this I'll make sure to cite the package Thanks again!

**Comment by phelipe** [comment]
@michaelmusty I will try do a example in Flux but I have to finish my thesis first.

**Comment by michaelmusty** [comment]
No rush @phelipe. If I get something working before then I will post it here.
